language: c
dist: trusty
sudo: required

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - packages
  - output

# Download and unpack the stack executable
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

env:
  - PATH=$HOME/purescript:$PATH

install:
  - TAG=v0.10.1
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript

script:
  - stack setup
  - stack build
  - stack exec verify-package-set
